### ISSUE TITLE
Device ZW31 from NIE Technology Unsupported?

### ISSUE THREAD

**Issue by nvOC-Stubo** [zwave-js/zwavejs2mqtt#1587]
### Version

**Checklist:**

- DEV Sent me here
- [ x] I have checked the troubleshooting section and my problem is **not** described there.
- [ x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 0.23.5
zwave-js version: 8.1.1

### Describe the bug

I was referred here by Frank as I had previously submitted this for the add-on. Yes, I am running Home Assistant (supervisor-2021.06.8).

On 0.23.5 (docker) adding ZW31 (NIE Technology Co., Ltd. / S2 In-wall Smart Dimmer switch) dimmers via Control Panel Action|Add/Remove Device|Inclusion (or Secure Inclusion) results in successful device addition but unknown manufacturer, product, and product code. The device works otherwise. Also, the control panel has a message at the top saying "Driver: Node XXX supports Security S2, but no network key was configured. Continuing interview non-securely".
On my Z-Wave JS to MQTT Control Panel, I see the following for these devices:
Manufacturer: 0x0312
Product: 0xaa00
Product Code: 0xaa02

When I look at the device database, that information seems to match this device entry which is the correct one:
https://devices.zwave-js.io/?jumpTo=0x0312:0xa000:0xaa02:0.0

I found the device (matching manufacturer, product, product code) in ~db/devices/index.json:
{
	"manufacturerId": "0x0312",
	"manufacturer": "NIE Technology Co., Ltd.",
	"label": "ZW31",
	"productType": "0xa000",
	"productId": "0xaa02",
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"filename": "0x0312/zw31.json",
	"rootDir": "/data/db/devices"
},

I have attached the logs and node info from where I added Node 59. Note: The references to zw31.json near the top of zwavejs_2021-08-24.log are a result my attempt at adding ZW31 support by dropping it in /store/config and can be ignored.
[ZW31_issue.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7041769/ZW31_issue.zip)

**Comment by blhoward2** [comment]
We need to verify but I believe this is likely the same device as Zooz's S2 switch. We may be able to copy over the file. 

In any event, this belongs under node-zwave-js. @robertsLando can you move it please?

**Comment by blhoward2** [comment]
```Also, the control panel has a message at the top saying "Driver: Node XXX supports Security S2, but no network key was configured. Continuing interview non-securely".```

This is an artifact of other pending S2 issues and is not specific to this device.

**Comment by nvOC-Stubo** [comment]
FWIW, it is actually branded as EVALOGIK: https://www.evalogik.com/smart-switch/z-wave-switch/zw31-z-wave-dimmer-paddle-switch.html
Z-wave but the details are as stated above. I would also like to get rid of the "pending S2 issues" but we can worry about that later.

**Comment by blhoward2** [comment]
The fix for that is already merged, clarifying the error message. It just hasn’t hit the release yet. https://github.com/zwave-js/node-zwave-js/pull/3229

Actually defining the keys is also merged.

**Comment by AlCalzone** [comment]
The above issue should be resolved.

**Comment by nvOC-Stubo** [comment]
It is better, but not resolved. The MFR is now known (NIE Technology) but the devices still show up as unknown - 0xaa00. I am running:
zwavejs2mqtt: 5.5.1
zwave-js: 8.2.1

**Comment by AlCalzone** [comment]
Can you share a driver log of a re-interview?

**Comment by nvOC-Stubo** [comment]
Sure, I think I captured the correct log.
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7155604/zwavejs2mqtt.log)

**Comment by AlCalzone** [comment]
That's not a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs). Please choose loglevel `debug` or `silly` and attach it here as a file.

**Comment by nvOC-Stubo** [comment]
Sorry about that. Driver log is attached.
[zwavejs_2021-09-13.log](https://github.com/zwave-js/zwavejs2mqtt/files/7156199/zwavejs_2021-09-13.log)

**Comment by AlCalzone** [comment]
Ahh... The file we have is for `productType: 0xa000`, your device has `productType: 0xaa00`.

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint 0xaa00:0xaa02 to 0x0312:0xa000:0xaa02:0.0
